//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio via: 
//     Edit > Paste Special > Paste JSON as Classes
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Inedo.Extensions.Loupe.Client.Model
{
    public class ApplicationVersionResponse
    {
        public ApplicationVersion[] data { get; set; }
        public int total { get; set; }
        public int page { get; set; }
        public int pageSize { get; set; }
        public object timeStamp { get; set; }
        public DateTime timeStampDisplay { get; set; }
    }

    public class ApplicationVersion
    {
        public Guid id { get; set; }
        public VersionData version { get; set; }
        public string caption { get; set; }
        public DateTime? releaseDate { get; set; }
        public string releaseType { get; set; }
        public string promotionLevel { get; set; }
        public object releaseNotes { get; set; }
    }

    public class VersionData
    {
        public string title { get; set; }
        public string url { get; set; }
        public string id { get; set; }
        public string productName { get; set; }
        public string applicationName { get; set; }
    }

}
