//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio via: 
//     Edit > Paste Special > Paste JSON as Classes
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inedo.Extensions.Loupe.Client.Model
{
    public class Error
    {
        public string message { get; set; }
    }
}
