//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio via: 
//     Edit > Paste Special > Paste JSON as Classes
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Inedo.Extensions.Loupe.Client.Model
{
    public class GetApplicationVersionResponse
    {
        public Version version { get; set; }
        public Lists lists { get; set; }
    }

    public class Version
    {
        public string description { get; set; }
        public Guid? promotionLevel { get; set; }
        public object releaseNotesUrl { get; set; }
        public string id { get; set; }
        public string applicationId { get; set; }
        public string version { get; set; }
        public long versionBin { get; set; }
        public string caption { get; set; }
        public string displayVersion { get; set; }
        public DateTime? releaseDate { get; set; }
        public Guid? releaseType { get; set; }
    }

    public class Lists
    {
        public Releasetype[] releaseTypes { get; set; }
        public Promotionlevel[] promotionLevels { get; set; }
    }

    public class Releasetype
    {
        public Guid id { get; set; }
        public string caption { get; set; }
    }

    public class Promotionlevel
    {
        public Guid id { get; set; }
        public string caption { get; set; }
    }
}
