//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio via: 
//     Edit > Paste Special > Paste JSON as Classes
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inedo.Extensions.Loupe.Client.Model
{
    public class ProductsAndApplicationsResponse
    {
        public Application[] data { get; set; }
    }

    public class Application
    {
        public string id { get; set; }
        public string productName { get; set; }
        public string applicationName { get; set; }
        public string productCaption { get; set; }
        public string applicationCation { get; set; }
        public string productApplicationCaption { get; set; }
    }

}
