//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Visual Studio via: 
//     Edit > Paste Special > Paste JSON as Classes
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Inedo.Extensions.Loupe.Client.Model
{
    public class TenantsForUserResponse
    {
        public Tenant[] tenants { get; set; }
        public string restrictedTenant { get; set; }
        public object[] expiredTenants { get; set; }
    }

    public class Tenant
    {
        public string tenantName { get; set; }
        public string tenantCaption { get; set; }
        public bool isTenantUser { get; set; }
        public string basePath { get; set; }
        public bool isExpired { get; set; }
        public DateTime expiresOn { get; set; }
        public bool isTrial { get; set; }
    }

}
